/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package poly.ass.ui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author cungtiennga
 */
public class HomeGV extends javax.swing.JFrame {

    Timer t,t1,t2;

    private String dataContructor;
    public HomeGV(String dataContructor) {
        initComponents();
        this.setLocationRelativeTo(null);
        showTTGV();
        showQLSV();
        showQLD();
        setTitle("Home Giảng Viên");
       this.dataContructor=dataContructor;
       this.txtUser.setText(dataContructor);
    
    }

    private HomeGV() {
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pgTienDo = new javax.swing.JProgressBar();
        txtUser = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuTTGV = new javax.swing.JMenuItem();
        mnuQLSV = new javax.swing.JMenuItem();
        mnuQLD = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Phosphate", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Chào Mừng Bạn Đến Home Giảng Viên");

        pgTienDo.setBackground(new java.awt.Color(255, 51, 51));
        pgTienDo.setStringPainted(true);

        txtUser.setEditable(false);

        jLabel2.setText("User:");

        jMenu1.setText("Quản lý");

        mnuTTGV.setText("Thông tin GV");
        mnuTTGV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTTGVActionPerformed(evt);
            }
        });
        jMenu1.add(mnuTTGV);

        mnuQLSV.setText("Quản lý SV");
        mnuQLSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuQLSVActionPerformed(evt);
            }
        });
        jMenu1.add(mnuQLSV);

        mnuQLD.setText("Quản lý điểm");
        mnuQLD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuQLDActionPerformed(evt);
            }
        });
        jMenu1.add(mnuQLD);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Đăng xuất");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 731, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pgTienDo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(223, 223, 223)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(27, 27, 27)
                .addComponent(pgTienDo, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuQLSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuQLSVActionPerformed
        // TODO add your handling code here:
        t1.start();

        
        

    }//GEN-LAST:event_mnuQLSVActionPerformed

    private void mnuQLDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuQLDActionPerformed
        // TODO add your handling code here:
        t2.start();

    }//GEN-LAST:event_mnuQLDActionPerformed

    private void mnuTTGVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTTGVActionPerformed
        // TODO add your handling code here:
        t.start();
        

    }//GEN-LAST:event_mnuTTGVActionPerformed

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        // TODO add your handling code here:
        int chon = JOptionPane.showConfirmDialog(this, "Bạn có muốn đăng xuất?", "Đăng xuất", JOptionPane.YES_NO_OPTION);
        if (chon == JOptionPane.YES_OPTION) {
            Login lg = new Login();
            this.dispose();
            lg.setVisible(true);
            lg.setLocationRelativeTo(null);
            this.setEnabled(true);
        }
    }//GEN-LAST:event_jMenu2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeGV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeGV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeGV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeGV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new HomeGV().setVisible(true);
            }
        });
    }

    public void showTTGV() {

        t = new Timer(10, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                pgTienDo.setValue(pgTienDo.getValue() + 1);
                if (pgTienDo.getValue() >= 100) {
                    // Dừng Timer
                    t.stop();

                    // Thực hiện các dòng code sau khi tiến trình hoàn thành
                    TTGV ttgv = new TTGV(txtUser.getText());
                    ttgv.setVisible(true);
                    ttgv.setLocationRelativeTo(null);
                    dispose();

                }

            }

        });

    }

    public void showQLSV() {
        t1 = new Timer(10, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                pgTienDo.setValue(pgTienDo.getValue() + 1);
                if (pgTienDo.getValue() >= 100) {
                    // Dừng Timer
                    t1.stop();

                    // Thực hiện các dòng code sau khi tiến trình hoàn thành
                    QLSVForm qlsvf = new QLSVForm();
                    qlsvf.setVisible(true);
                    qlsvf.setLocationRelativeTo(null);
                    dispose();
                }

            }

        });
    }

    public void showQLD() {
        t2 = new Timer(10, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                pgTienDo.setValue(pgTienDo.getValue() + 1);
                if (pgTienDo.getValue() >= 100) {
                    // Dừng Timer
                    t2.stop();

                    // Thực hiện các dòng code sau khi tiến trình hoàn thành
                    QLDiemUI diemUI = new QLDiemUI();
                    diemUI.setVisible(true);
                    diemUI.setLocationRelativeTo(null);
                    dispose();
                }

            }

        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mnuQLD;
    private javax.swing.JMenuItem mnuQLSV;
    private javax.swing.JMenuItem mnuTTGV;
    private javax.swing.JProgressBar pgTienDo;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
